"""empty message

Revision ID: 3e78797f2aef
Revises: 365f4721caf1
Create Date: 2023-09-19 14:53:39.562381

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e78797f2aef'
down_revision = '365f4721caf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lga')
    op.drop_table('state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state',
    sa.Column('state_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('state_name', mysql.VARCHAR(length=80), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('state_id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('lga',
    sa.Column('lga_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('state_id', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('lga_name', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('lga_id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
