"""empty message

Revision ID: cd83d68b117b
Revises: 2d80ca4b8edb
Create Date: 2023-09-20 13:22:47.146905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd83d68b117b'
down_revision = '2d80ca4b8edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contactus',
    sa.Column('contact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.drop_table('contact')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('contact_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('contact_email', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('contact_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('contactus')
    # ### end Alembic commands ###
